CREATE TABLE Customer (
  CustomerID NUMBER PRIMARY KEY,
  Name VARCHAR2(100) NOT NULL,
  Email VARCHAR2(100) UNIQUE NOT NULL,
  Password VARCHAR2(100) NOT NULL,
  Address VARCHAR2(255)
);

CREATE SEQUENCE Customer_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER Customer_before_insert
BEFORE INSERT ON Customer
FOR EACH ROW
BEGIN
  SELECT Customer_seq.NEXTVAL INTO :NEW.CustomerID FROM dual;
END;
/
CREATE TABLE Book (
  BookID NUMBER PRIMARY KEY,
  Title VARCHAR2(200) NOT NULL,
  Author VARCHAR2(100) NOT NULL,
  ISBN VARCHAR2(20) UNIQUE NOT NULL,
  Price NUMBER(10,2) NOT NULL,
  StockQty NUMBER DEFAULT 0
);

CREATE SEQUENCE Book_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER Book_before_insert
BEFORE INSERT ON Book
FOR EACH ROW
BEGIN
  SELECT Book_seq.NEXTVAL INTO :NEW.BookID FROM dual;
END;
/
CREATE TABLE OrderTable (
  OrderID NUMBER PRIMARY KEY,
  CustomerID NUMBER NOT NULL,
  OrderDate DATE DEFAULT SYSDATE,
  TotalAmount NUMBER(10,2) NOT NULL,
  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE SEQUENCE Order_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER Order_before_insert
BEFORE INSERT ON OrderTable
FOR EACH ROW
BEGIN
  SELECT Order_seq.NEXTVAL INTO :NEW.OrderID FROM dual;
END;
/
CREATE TABLE OrderItem (
  OrderItemID NUMBER PRIMARY KEY,
  OrderID NUMBER NOT NULL,
  BookID NUMBER NOT NULL,
  Quantity NUMBER NOT NULL,
  FOREIGN KEY (OrderID) REFERENCES OrderTable(OrderID),
  FOREIGN KEY (BookID) REFERENCES Book(BookID)
);

CREATE SEQUENCE OrderItem_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER OrderItem_before_insert
BEFORE INSERT ON OrderItem
FOR EACH ROW
BEGIN
  SELECT OrderItem_seq.NEXTVAL INTO :NEW.OrderItemID FROM dual;
END;
/
CREATE PROFILE BasicProfile LIMIT
  FAILED_LOGIN_ATTEMPTS 3;
CREATE USER C##Moe IDENTIFIED BY chriskhalil;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE SESSION TO C##Moe;
ALTER USER C##Moe PROFILE BasicProfile;
CREATE ROLE adminRole;
GRANT adminRole TO C##Moe;
GRANT SELECT, INSERT ON Book TO C##Moe;
GRANT SELECT, INSERT ON Customer TO C##Moe;
-- Example: Grant limited privileges
GRANT CREATE SESSION, SELECT ANY TABLE TO adminRole;

-- System privileges
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'C##Moe';

-- Object privileges
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'C##Moe';

-- Roles granted
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'C##Moe';